#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
LAB_DIR=$(cd "$SCRIPT_DIR/.." && pwd)
EVIDENCE_DIR="$LAB_DIR/evidence"

: "${RG:?Set RG to the lab resource group name before running this script.}"
: "${VM_NAME:?Set VM_NAME to the deployed virtual machine name before running this script.}"

if ! command -v az >/dev/null 2>&1; then
  printf 'Azure CLI is required but was not found on PATH.\n' >&2
  exit 1
fi

if ! command -v nc >/dev/null 2>&1; then
  printf 'netcat (nc) is required but was not found on PATH.\n' >&2
  exit 1
fi

mkdir -p "$EVIDENCE_DIR"

NIC_NAME=$(az vm show --resource-group "$RG" --name "$VM_NAME" --query 'networkProfile.networkInterfaces[0].id' --output tsv | awk -F/ '{print $NF}')
PUBLIC_IP=$(az vm show --resource-group "$RG" --name "$VM_NAME" --show-details --query publicIps --output tsv)

az network nic list-effective-nsg \
  --resource-group "$RG" \
  --name "$NIC_NAME" \
  --output json > "$EVIDENCE_DIR/effective-nsg.json"

{
  printf '# Live capture generated by labs/cannot-rdp-or-ssh/scripts/reproduce.sh\n'
  printf '# RG=%s VM_NAME=%s\n' "$RG" "$VM_NAME"
  nc -vz -w 5 "$PUBLIC_IP" 22
} > "$EVIDENCE_DIR/connection-test.txt" 2>&1 || true

printf 'Captured evidence:\n'
printf '  %s\n' "$EVIDENCE_DIR/connection-test.txt"
printf '  %s\n' "$EVIDENCE_DIR/effective-nsg.json"
